#!/usr/bin/env python
"""Atlas Phase 11 — THE CAPSTONE: the small-parameter structural model (the platonic-solid model).

Kepler's Mysterium derived the cosmos from nested platonic solids — beautiful, generative, and WRONG
(planets are not generated by the solids). The halo atlas is that instinct on the object where it is TRUE:
the display IS generated by a small discrete set of crystal forms. This module makes the claim PRECISE and
CHECKABLE — the whole classified atlas is FORWARD-GENERATED from a tiny parameter set, and everything
recomputes from the one continuous physical parameter n (the derived-not-hardcoded demonstration).

THE PARAMETER ACCOUNTING (the small-parameter claim, made literal):
  • 1 continuous physical parameter:  n = 1.31  (refractive index; visible centroid, chromatic 1.306–1.317).
      -> sets EVERY fold-ring radius and EVERY admissibility wall.
  • 0 free geometric parameters:  the ice Ih lattice is a FIXED input, not a fit —
      hexagonal 6-fold symmetry + c/a = 1.628 (=> the {10-11} pyramid angle 62°) + the face set
      {prism {10-10}, basal {0001}, pyramid {10-11}}. The refracting wedges (60°, 90°, the odd Galle
      wedges) are DERIVED from these face normals.
  • a discrete enumeration of ~7 habits (the aerodynamic falling-orientation modes = the "platonic solids"):
      random(3-DOF) · plate(1) · column(2) · Parry(1) · Lowitz(2) · pyramidal · bullet-rosette.
  • control:  sun elevation h (the phase-diagram axis) + the per-habit orientation manifold (swept).
From {n, ice geometry, habit list} the classified atlas falls out — the fold radii, the walls, the caustic
catastrophes (A2 folds / A3 cusps / the 29.7° A3-class merge / the Lowitz A3-lips), the 21-cell phase
diagram, and the Berry-confirmed NO A4 swallowtail / NO D4 umbilic. NOT public-eligible.
"""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from s2_optics import halo_min_deviation
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # Windows cp1252 console robustness
except Exception:
    pass

ICE_A, ICE_C = 4.519, 7.357          # ice Ih lattice constants (Angstrom); c/a = 1.628 (a FIXED input)
ICE_CA = ICE_C / ICE_A
N_VIS = 1.31                          # the one continuous physical parameter (visible centroid)

# the discrete habit enumeration (the "platonic solids" of the halo world) + their orientation DOF
HABITS = {
    "random": 3, "plate": 1, "column": 2, "Parry": 1, "Lowitz": 2, "pyramidal": "0/2/3", "bullet-rosette": "~3",
}


def pyramid_angle(ca=ICE_CA):
    """The {10-11} pyramid-face normal angle from the c-axis — DERIVED from the ice c/a ratio, NOT free."""
    return math.degrees(math.acos(1.0 / math.sqrt((4.0 / 3.0) * ca * ca + 1.0)))


def generate_atlas(n):
    """Forward-generate the quantitative atlas SKELETON from n (+ the fixed ice geometry). Every value here
    is a FUNCTION of n — vary n and the whole table shifts (the recompute-from-n = derived-not-hardcoded
    demonstration). The slow caustic transitions (29.7° merge, 16.1° Lowitz A3-lips) are functions of n too,
    via the forward map (atlas_forward_sweep / atlas_caustic_map); kept out of this fast closed-form core."""
    sq = math.sqrt(n * n - 1.0)
    return {
        "fold_radii_deg": {                                   # A2 fold rings = f(n, wedge angle)
            "22 halo": halo_min_deviation(60, n), "46 halo": halo_min_deviation(90, n),
            "9 odd": halo_min_deviation(28.0, n), "18 odd": halo_min_deviation(52.4, n),
            "20 odd": halo_min_deviation(56.0, n), "24 odd": halo_min_deviation(63.8, n),
            "35 odd": halo_min_deviation(80.2, n),
        },
        "walls_deg": {                                        # component-B admissibility walls = f(n)
            "CZA_off": math.degrees(math.acos(sq)),
            "CHA_on": math.degrees(math.asin(sq)),
            "TIR_critical": math.degrees(math.asin(1.0 / n)),
        },
    }


def main():
    print("Atlas Phase 11 — THE CAPSTONE: the small-parameter structural (platonic-solid) model\n")
    print(f"  Parameter set: 1 continuous physical param (n={N_VIS}); 0 free geometric params (ice Ih:")
    print(f"    hexagonal 6-fold + c/a={ICE_CA:.3f} -> pyramid angle {pyramid_angle():.2f}° + the face set);")
    print(f"    {len(HABITS)} discrete habits {list(HABITS)}; control = sun elevation h + orientation.\n")

    a = generate_atlas(N_VIS)
    print("  The atlas skeleton generated from n (fold-ring radii + admissibility walls):")
    print("    A2 fold rings:  " + "  ".join(f"{k}={v:.2f}°" for k, v in a["fold_radii_deg"].items()))
    print("    B walls:        " + "  ".join(f"{k}={v:.3f}°" for k, v in a["walls_deg"].items())
          + f"   (CZA+CHA={a['walls_deg']['CZA_off'] + a['walls_deg']['CHA_on']:.3f}°)")

    print("\n  RECOMPUTE-FROM-n (the derived-not-hardcoded demonstration): vary n -> the whole table shifts.")
    b = generate_atlas(1.40)
    print(f"    {'quantity':>14}{'n=1.31':>12}{'n=1.40':>12}{'shift':>10}")
    for k in ("22 halo", "46 halo", "9 odd"):
        print(f"    {k:>14}{a['fold_radii_deg'][k]:>11.2f}°{b['fold_radii_deg'][k]:>11.2f}°"
              f"{b['fold_radii_deg'][k] - a['fold_radii_deg'][k]:>+9.2f}°")
    for k in ("CZA_off", "CHA_on"):
        print(f"    {k:>14}{a['walls_deg'][k]:>11.3f}°{b['walls_deg'][k]:>11.3f}°"
              f"{b['walls_deg'][k] - a['walls_deg'][k]:>+9.2f}°")
    print("    => every number moves with n: the atlas is GENERATED (a function of n), not a list of "
          "constants.")
    print("\n  The caustic catastrophes (29.7° merge, 16.1° Lowitz A3-lips) + the 21-cell phase diagram are")
    print("  forward-generated by the same parameters (atlas_forward_sweep.py); the higher strata are EMPTY")
    print("  (Berry confirmed: NO A4 swallowtail, NO D4 umbilic) — the platonic-solid dream, made checkable.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
