#!/usr/bin/env python
r"""BoxSEL Phase 4f - the n=2 endpoint-order atlas (lower-bound closure, harder half).

Phase 4e proved q_KKT = (9 + sqrt 17)/32 is minimal inside the structured 2-D normal form. This
module attacks the next obligation: rule out EVERY n=2 combinatorial cell (interval-endpoint
ordering), not just the structured one. It is a START, honestly scoped.

THE ATLAS (certified, exact combinatorics):

* Per axis a "cell" is the arrangement of the three pairwise-overlapping intervals A, B, C: a pair
  (sigma, tau) where sigma orders the LEFT endpoints and tau the RIGHT endpoints (atoms 0=A,1=B,2=C).
  Overlap formulas depend only on (sigma, tau), so there are exactly 6 x 6 = 36 per-axis types.
* The symmetry group is generated by A<->B (the query is symmetric in A,B), the reflection x->1-x
  (swaps left/right roles and reverses both orders), and -- for n=2 -- the axis swap.
* Counts: 36 per-axis types -> 12 per-axis orbits; 36 x 36 = 1296 n=2 cell-pairs -> 123 orbits.

EXACT STRUCTURAL ELIMINATION:

* On an axis, C "helps" (lets q_k < 1) iff C sticks out of A_k & B_k, i.e. C has the strictly
  largest left (sigma ends in C) OR the strictly smallest right (tau starts with C). Otherwise
  C ⊇ A_k & B_k and q_k = 1.
* A cell with ZERO helping axes forces q = q_1 q_2 = 1 >= q_KKT -- eliminated exactly. There are 31
  such orbits. That leaves 92 "live" orbits (56 one-help + 36 two-help; q_KKT lives in the two-help
  family, on a degenerate boundary where B_1 and C_1 share a left endpoint).

STATUS. Certified: the enumeration (123 orbits) and the exact elimination of the 31 zero-help
orbits. Numerical backstop (NOT a per-cell exact proof): a search seeded from the optimum's full
symmetry orbit over the live cells finds nothing below q_KKT (see ATLAS_SEEDED_SEARCH_MIN). Open
for full rigor: an exact per-cell minimum for each of the 92 live orbits, then the n>=3 compression.

Global sandwich is UNCHANGED and honest:  1/4 <= inf I_box^n <= (9 + sqrt 17)/32.
"""
from fractions import Fraction
from itertools import permutations, product

import boxsel_kkt_exact as kkt

F = Fraction
A, B, C = 0, 1, 2
ATOM_NAMES = {0: "A", 1: "B", 2: "C"}

GLOBAL_LOWER_BOUND_CLOSED = False
Q_KKT = kkt.Q_STAR
# Numerical backstop: best q a symmetry-orbit-seeded Nelder-Mead search reached over the live
# cells (>= q_KKT; reproduced by tools in this phase). It is evidence, not a per-cell exact proof.
ATLAS_SEEDED_SEARCH_MIN = 0.4100970  # ~= q_KKT; search found nothing strictly below

REMAINING_GLOBAL_OBLIGATIONS = (
    "exact per-cell minimum for each of the 92 live n=2 orbits (56 one-help + 36 two-help).",
    "dimension compression: prove n>=3 cannot beat the 2-D optimum, or find a counterexample.",
)


# --- the combinatorial atlas (exact) ---

def per_axis_types() -> list:
    """All 36 per-axis cells (sigma, tau): orderings of the 3 left and 3 right endpoints."""
    perms = list(permutations(range(3)))
    return [(s, t) for s in perms for t in perms]


def _swap_ab_perm(p):
    m = {A: B, B: A, C: C}
    return tuple(m[i] for i in p)


def reflect(cell):
    """x -> 1-x: left/right roles swap and both orders reverse."""
    s, t = cell
    return (t[::-1], s[::-1])


def swap_ab(cell):
    s, t = cell
    return (_swap_ab_perm(s), _swap_ab_perm(t))


def _axis_orbit(cell) -> frozenset:
    seen, frontier = set(), [cell]
    while frontier:
        c = frontier.pop()
        if c in seen:
            continue
        seen.add(c)
        frontier += [reflect(c), swap_ab(c)]
    return frozenset(seen)


def per_axis_orbits() -> list:
    return [min(o) for o in {_axis_orbit(c) for c in per_axis_types()}]


def _reflect_axis(pair, k):
    p = list(pair)
    p[k] = reflect(p[k])
    return tuple(p)


def _swap_ab_pair(pair):
    return tuple(swap_ab(c) for c in pair)  # A<->B is a global relabel (both axes)


def _swap_axes(pair):
    return (pair[1], pair[0])


def _pair_orbit(pair) -> frozenset:
    seen, frontier = set(), [pair]
    while frontier:
        c = frontier.pop()
        if c in seen:
            continue
        seen.add(c)
        frontier += [_reflect_axis(c, 0), _reflect_axis(c, 1), _swap_ab_pair(c), _swap_axes(c)]
    return frozenset(seen)


def n2_orbits() -> list:
    """Canonical representatives of the 123 n=2 cell-pair orbits."""
    reps = {}
    for pair in product(per_axis_types(), per_axis_types()):
        reps[_pair_orbit(pair)] = min(_pair_orbit(pair))
    return list(reps.values())


def helps(axis_cell) -> bool:
    """True iff C can stick out of A&B on this axis (C largest-left or smallest-right)."""
    s, t = axis_cell
    return s[2] == C or t[0] == C


def classify_orbits() -> dict:
    """Count n=2 orbits by number of helping axes (0 => q=1 forced)."""
    counts = {0: 0, 1: 0, 2: 0}
    for rep in n2_orbits():
        counts[sum(helps(rep[k]) for k in (0, 1))] += 1
    return counts


# --- exact geometric realization (to validate the helps/q=1 criterion) ---

def realize_axis(axis_cell, left_vals, right_vals) -> dict:
    """Build the three intervals (Fraction) for a per-axis cell from sorted left/right values."""
    s, t = axis_cell
    lefts, rights = [F(v) for v in sorted(left_vals)], [F(v) for v in sorted(right_vals)]
    left_of = {s[i]: lefts[i] for i in range(3)}
    right_of = {t[i]: rights[i] for i in range(3)}
    return {atom: (left_of[atom], right_of[atom]) for atom in (A, B, C)}


def axis_q(intervals) -> Fraction:
    """q_k = |A&B&C| / |A&B| on one axis (Fraction)."""
    def ov(*atoms):
        lo = max(intervals[a][0] for a in atoms)
        hi = min(intervals[a][1] for a in atoms)
        return hi - lo if hi > lo else F(0)
    ab = ov(A, B)
    if ab == 0:
        return F(1)
    return ov(A, B, C) / ab


def certified_sandwich():
    """(lower, candidate_upper): 1/4 <= inf I_box^n <= (9 + sqrt 17)/32 (UNCHANGED by 4f)."""
    return kkt.CERTIFIED_LOWER, Q_KKT


if __name__ == "__main__":
    import sys
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    print("per-axis types:", len(per_axis_types()), " per-axis orbits:", len(per_axis_orbits()))
    print("n=2 cell-pairs:", 36 * 36, " n=2 orbits:", len(n2_orbits()))
    print("orbits by #helping-axes:", classify_orbits(), "(0-help => q=1, exact-eliminated)")
    print("global lower bound closed:", GLOBAL_LOWER_BOUND_CLOSED, " sandwich:", certified_sandwich())
    print("seeded-search min over live cells ~=", ATLAS_SEEDED_SEARCH_MIN, " (>= q_KKT ~=", float(Q_KKT), ")")
