#!/usr/bin/env node
// scripts/build-sitemap.mjs
//
// Generate public/sitemap.xml from site-pages.json so it never drifts again.
// Root cause of "sundog.cc not sitemapped well": the sitemap was hand-maintained,
// so new pages (e.g. p-vs-np) were missed and every <lastmod> was frozen at the
// file's creation date. This derives the sitemap from the page manifest with two
// honest, self-maintaining rules:
//
//   INCLUSION RULE (a page is in the sitemap iff BOTH hold):
//     1. its HTML has no `<meta name="robots" ... noindex ...>`  (indexable), and
//     2. it is self-canonical — its <link rel="canonical"> points at its own
//        clean URL, not at another page. (This drops duplicate/absorbed surfaces
//        like sundog-workbench, whose canonical is /sundog.)
//
//   LASTMOD: the file's last git commit date (real freshness signal), falling
//   back to filesystem mtime if git is unavailable.
//
// Wired into prebuild. Run standalone: `node scripts/build-sitemap.mjs`
// Use `--check` to fail (exit 1) if the on-disk sitemap is stale vs a fresh
// generation — useful in CI / pre-deploy.

import { readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ORIGIN = "https://sundog.cc";
const OUT = path.resolve(REPO, "public/sitemap.xml");

function slugFor(entry) {
  // index.html -> "" (root); foo.html -> "foo"
  const base = entry.replace(/\.html$/, "");
  return base === "index" ? "" : base;
}

function cleanUrl(slug) {
  return slug === "" ? `${ORIGIN}/` : `${ORIGIN}/${slug}`;
}

function isNoindex(html) {
  const m = html.match(/<meta[^>]+name=["']robots["'][^>]*>/i);
  return m ? /noindex/i.test(m[0]) : false;
}

function selfCanonical(html, slug) {
  const m = html.match(/<link[^>]+rel=["']canonical["'][^>]*>/i);
  if (!m) return true; // no canonical declared -> treat as self
  const href = (m[0].match(/href=["']([^"']+)["']/i) || [])[1];
  if (!href) return true;
  const want = cleanUrl(slug).replace(/\/$/, "");
  const got = href.replace(/\/$/, "");
  return want === got;
}

function gitLastModified(entry) {
  try {
    const iso = execFileSync("git", ["log", "-1", "--format=%cs", "--", entry], {
      cwd: REPO, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) return iso;
  } catch { /* fall through */ }
  try {
    return statSync(path.resolve(REPO, entry)).mtime.toISOString().slice(0, 10);
  } catch {
    return null;
  }
}

function buildSitemap() {
  const manifest = JSON.parse(readFileSync(path.resolve(REPO, "site-pages.json"), "utf8"));
  const rows = [];
  const excluded = [];
  for (const page of manifest.pages ?? []) {
    const entry = page.entry;
    const abs = path.resolve(REPO, entry);
    if (!existsSync(abs)) { excluded.push({ entry, reason: "file missing" }); continue; }
    const html = readFileSync(abs, "utf8");
    const slug = slugFor(entry);
    if (isNoindex(html)) { excluded.push({ entry, reason: "noindex" }); continue; }
    if (!selfCanonical(html, slug)) { excluded.push({ entry, reason: "non-self-canonical (duplicate surface)" }); continue; }
    rows.push({ entry, loc: cleanUrl(slug), lastmod: gitLastModified(entry) });
  }
  // Stable order: root first, then alphabetical by loc — deterministic output.
  rows.sort((a, b) => (a.loc === `${ORIGIN}/` ? -1 : b.loc === `${ORIGIN}/` ? 1 : a.loc.localeCompare(b.loc)));

  const body = rows.map((r) => {
    const lm = r.lastmod ? `\n    <lastmod>${r.lastmod}</lastmod>` : "";
    return `  <url>\n    <loc>${r.loc}</loc>${lm}\n  </url>`;
  }).join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Sundog sitemap. GENERATED by scripts/build-sitemap.mjs from site-pages.json.
  Do not hand-edit: changes are overwritten on the next build. Inclusion rule:
  indexable (no noindex) AND self-canonical. lastmod = last git commit date.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
  return { xml, rows, excluded };
}

function main() {
  const check = process.argv.includes("--check");
  const { xml, rows, excluded } = buildSitemap();

  if (check) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
    if (current.trim() !== xml.trim()) {
      console.error("sitemap STALE: public/sitemap.xml differs from a fresh generation. Run `node scripts/build-sitemap.mjs`.");
      process.exitCode = 1;
      return;
    }
    console.log(`sitemap OK: ${rows.length} URLs, up to date.`);
    return;
  }

  writeFileSync(OUT, xml, "utf8");
  console.log(`sitemap written: public/sitemap.xml (${rows.length} URLs)`);
  console.log(`  excluded ${excluded.length}: ${excluded.map((e) => `${e.entry} [${e.reason}]`).join(", ")}`);
}

main();
