// Ghost Phase 3 aperiodic reader core.
//
// Pure logic for the internal reader at ghost/aperiodic.html and the Node
// acceptance tests in scripts/ghost-aperiodic-tests.mjs.
//
// Substrate: rhombic Penrose tiling (P3), generated by Robinson-triangle
// deflation (see docs/ghost/PHASE3_APERIODIC_READER_SPEC.md section 2). This is
// not a tiling theorem probe. It renders a known aperiodic substrate and makes
// its inflation hierarchy / recognizability visible to a reader. No new Ghost
// invariant is claimed.

export const GOLDEN = (1 + Math.sqrt(5)) / 2; // phi
export const RED = 0; // half of the THIN rhombus (acute, 36 deg apex)
export const BLUE = 1; // half of the THICK rhombus (obtuse, 108 deg)
export const DEFAULT_DEPTH = 6;

export function rhombusOf(color) {
  return color === RED ? "thin" : "thick";
}

// --- point helpers (plain {x, y}) ---
function sub(a, b) {
  return { x: a.x - b.x, y: a.y - b.y };
}
// A + (B - A) / phi : the golden cut point from A toward B.
function goldenCut(a, b) {
  const d = sub(b, a);
  return { x: a.x + d.x / GOLDEN, y: a.y + d.y / GOLDEN };
}
export function distance(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y);
}
export function centroid(tri) {
  return {
    x: (tri.A.x + tri.B.x + tri.C.x) / 3,
    y: (tri.A.y + tri.B.y + tri.C.y) / 3,
  };
}

// Seed: a decagon "sun" of 10 RED triangles around the origin, alternating
// mirror orientation. Far vertices sit on the unit circle; apex at origin.
export function baseWheel() {
  const tris = [];
  for (let i = 0; i < 10; i++) {
    let B = { x: Math.cos(((2 * i - 1) * Math.PI) / 10), y: Math.sin(((2 * i - 1) * Math.PI) / 10) };
    let C = { x: Math.cos(((2 * i + 1) * Math.PI) / 10), y: Math.sin(((2 * i + 1) * Math.PI) / 10) };
    if (i % 2 === 0) {
      const t = B;
      B = C;
      C = t;
    }
    tris.push({ color: RED, A: { x: 0, y: 0 }, B, C, path: [i] });
  }
  return tris;
}

// One deflation step. Verified subdivision rule:
//   RED  (A,B,C): P=goldenCut(A,B); children RED(C,P,B), BLUE(P,C,A)
//   BLUE (A,B,C): Q=goldenCut(B,A); R=goldenCut(B,C);
//                 children BLUE(R,C,A), BLUE(Q,R,B), RED(R,Q,A)
export function subdivideOnce(triangles) {
  const out = [];
  for (const t of triangles) {
    const { A, B, C, path } = t;
    if (t.color === RED) {
      const P = goldenCut(A, B);
      out.push({ color: RED, A: C, B: P, C: B, path: [...path, 0] });
      out.push({ color: BLUE, A: P, B: C, C: A, path: [...path, 1] });
    } else {
      const Q = goldenCut(B, A);
      const R = goldenCut(B, C);
      out.push({ color: BLUE, A: R, B: C, C: A, path: [...path, 0] });
      out.push({ color: BLUE, A: Q, B: R, C: B, path: [...path, 1] });
      out.push({ color: RED, A: R, B: Q, C: A, path: [...path, 2] });
    }
  }
  return out;
}

export function makePenrose(depth = DEFAULT_DEPTH) {
  let tris = baseWheel();
  for (let i = 0; i < depth; i++) tris = subdivideOnce(tris);
  return { depth, triangles: tris };
}

export function countsByType(triangles) {
  let red = 0;
  let blue = 0;
  for (const t of triangles) {
    if (t.color === RED) red++;
    else blue++;
  }
  return { red, blue };
}

// thick:thin rhombus ratio == blue:red triangle ratio (2 same-color triangles
// per rhombus). Returns Infinity when there are no red/thin triangles.
export function thickThinRatio(triangles) {
  const { red, blue } = countsByType(triangles);
  return red === 0 ? Infinity : blue / red;
}

export function maxAncestryLevel(model) {
  return model.depth;
}

// Supertile key for a finest tile at ancestry level k (k inflation steps up).
// level 0 -> unique per finest tile; level k -> the ancestor k steps up.
export function supertileKey(tri, level) {
  const keep = Math.max(0, tri.path.length - level);
  return tri.path.slice(0, keep).join("/");
}

export function clampInt(value, min, max) {
  const n = Number.isFinite(Number(value)) ? Math.trunc(Number(value)) : min;
  return Math.max(min, Math.min(max, n));
}

// Group finest tiles by supertile at the given ancestry level.
export function supertilesAtLevel(model, level) {
  const safe = clampInt(level, 0, model.depth);
  const groups = new Map();
  for (const t of model.triangles) {
    const key = supertileKey(t, safe);
    let g = groups.get(key);
    if (!g) {
      g = { key, tiles: [] };
      groups.set(key, g);
    }
    g.tiles.push(t);
  }
  return [...groups.values()];
}

function triVerticesInside(tri, center, r) {
  return [tri.A, tri.B, tri.C].filter((v) => distance(v, center) <= r).length;
}

// Window / recognizability analysis at a chosen ancestry level. A supertile is
// "contained" (ancestry recoverable from inside) if every vertex of every tile
// lies in the window; "crossing" (ghost at the boundary) if it touches the
// window but is not contained.
export function analyzeWindow(model, center, radius, level) {
  const safeLevel = clampInt(level, 1, model.depth);
  const r = radius;
  const finest = model.triangles;
  const counts = countsByType(finest);

  let tilesInWindow = 0;
  for (const t of finest) {
    if (distance(centroid(t), center) <= r) tilesInWindow++;
  }

  const groups = supertilesAtLevel(model, safeLevel);
  let touching = 0;
  let contained = 0;
  let crossing = 0;
  for (const g of groups) {
    let anyIn = false;
    let allIn = true;
    for (const t of g.tiles) {
      const nIn = triVerticesInside(t, center, r);
      if (nIn > 0) anyIn = true;
      if (nIn < 3) allIn = false;
      if (anyIn && !allIn) break;
    }
    if (!anyIn) continue;
    touching++;
    if (allIn) contained++;
    else crossing++;
  }

  return {
    substrate: "penrose-p3",
    regime: "bounded recognition (Penrose is recognizable / unique composition)",
    note:
      crossing === 0
        ? "every touched supertile is fully inside the window: ancestry is recoverable, the ghost has collapsed at this level"
        : "some supertiles cross the window edge: their ancestry is ghost at the boundary until the window grows or the level drops",
    depth: model.depth,
    ancestryLevel: safeLevel,
    window: { center, radius: r },
    tileCounts: { thin: counts.red, thick: counts.blue, total: counts.red + counts.blue },
    thickThinRatio: thickThinRatio(finest),
    tilesInWindow,
    supertilesTouching: touching,
    supertilesContained: contained,
    supertilesCrossing: crossing,
    cliff: {
      label: "computability cliff",
      active: false,
      note: "General Wang/SFT extension can encode computation. This reader does not measure that regime.",
    },
  };
}

// Per-supertile window status for rendering: 'contained' (ancestry recoverable
// from inside the window), 'crossing' (ghost at the boundary), or 'outside'.
export function classifySupertiles(model, center, radius, level) {
  const groups = supertilesAtLevel(model, clampInt(level, 1, model.depth));
  const status = new Map();
  for (const g of groups) {
    let anyIn = false;
    let allIn = true;
    for (const t of g.tiles) {
      const nIn = triVerticesInside(t, center, radius);
      if (nIn > 0) anyIn = true;
      if (nIn < 3) allIn = false;
    }
    status.set(g.key, anyIn ? (allIn ? "contained" : "crossing") : "outside");
  }
  return status;
}

export function exportReaderAnalysis(model, center, radius, level) {
  const a = analyzeWindow(model, center, radius, level);
  return {
    substrate: a.substrate,
    regime: a.regime,
    depth: a.depth,
    ancestryLevel: a.ancestryLevel,
    window: a.window,
    tileCounts: a.tileCounts,
    thickThinRatio: a.thickThinRatio,
    tilesInWindow: a.tilesInWindow,
    supertilesTouching: a.supertilesTouching,
    supertilesContained: a.supertilesContained,
    supertilesCrossing: a.supertilesCrossing,
    cliff: a.cliff,
  };
}
